# This is a basic workflow to help you get started with Actions

name: on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    # Matrix strategy to define different operating systems 
    strategy:
      matrix:
          os: [windows-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Sets up the java version
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'     

      # Runs a single command using the runners shell
      - name: build gui mitarbeiter
        shell: bash        
        working-directory: ${{github.workspace}}
        run: javac -cp "src/libs/*" -d builds src/klassen/*.java

      - name: Upload Compliled Classes
        uses: actions/upload-artifact@v3
        with:
          name: my-application
          path: ./builds/klassen/*.class

      - name: Upload libs
        uses: actions/upload-artifact@v3
        with:
          name: my-libs
          path: ./src/libs/*.jar
       #note to self: until here, all good. 
       
  run-app:
    runs-on: windows-latest
    needs: build

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Sets up the java version
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          
      - name: Download application from build job
        uses: actions/download-artifact@v3
        with:
          name: my-application
          path: my-application/klassen
      
      #download libs
      - name: Download javafx and derby jars
        uses: actions/download-artifact@v3
        with:
          name: my-libs
          path: my-application/libs
          
      # test dir command
      - name: run dir
        shell: bash        
        working-directory: ${{github.workspace}}/my-application
        run: dir

      # Runs a single command using the runners shell
      - name: run gui mitarbeiter
        shell: bash        
        working-directory: ${{github.workspace}}/my-application
        run: java klassen.GUI_Mitarbeiter
